export const API_CONFIG = {
  MAX_FIRSTNAME_LENGTH: 20,
  MIN_FIRSTNAME_LENGTH: 2,
  MAX_LASTNAME_LENGTH: 20,
  MIN_LASTNAME_LENGTH: 2,
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 30,
  MIN_METRICS_NAME_LENGTH: 2,
  MAX_METRICS_NAME_LENGTH: 20,
  MIN_DESIRED_METRICS_VALUE: 1,
};
