FROM node:alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY dist/apps/client/browser ./monotor-client-dist

COPY scripts/static-client-server.js ./

EXPOSE 2202

CMD ["node", "static-client-server.js"]