FROM node:alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY dist/apps/server ./server-dist

RUN mkdir -p /app/data /app/logs

EXPOSE 3000

CMD ["node", "server-dist/main.js"]