export enum ExceptionStatusKeys {
  NotFound = 'errors.not_found',
  Forbidden = 'errors.forbidden',
  BadRequest = 'errors.bad_request',
  PaymentRequired = 'errors.payment_required',
  Unauthorized = 'errors.unauthorized',
  Conflict = 'errors.conflict',
  Teapot = 'errors.teapot',
  ContentTooLarge = 'errors.content_too_large',
  UnsupportedMediaType = 'errors.unsupported_media_type',
  EnhanceYourCalm = 'errors.enhance_your_calm',
  InternalServerError = 'errors.internal_server_error',
}

export enum GlobalExceptionKeys {
  IncorrectMongooseID = 'errors.incorrect_mongoose_id',
  PageIndexNotNumber = 'errors.page_index.not_number',
  PageIndexTooLow = 'errors.page_index.too_low',
  PageSizeNotNumber = 'errors.page_size.not_number',
  PageSizeTooLow = 'errors.page_size.too_low',
  PageSizeTooHigh = 'errors.page_size.too_high',
  EndPointNotFound = 'errors.endpoint_not_found',
  InvalidJSON = 'errors.invalid_json',
  NothingToUpdate = 'errors.nothing_to_update',
}

export enum AuthExpectionKeys {
  IncorrectEmailOrPassword = 'errors.incorrect_email_or_password',
  EmailInUse = 'errors.email_in_use',
  TokenInvalid = 'errors.token_invalid',
  TokenExpired = 'errors.token_expired',
  TokenNotFound = 'errors.token_not_found',
  InvalidEmail = 'errors.invalid_email',
  InvalidPassword = 'errors.invalid_password',
  InvalidOldPassword = 'errors.invalid_old_password',
  InvalidChangePassword = 'errors.invalid_change_password',
  FirstnameTooLong = 'errors.firstname_too_long',
  FirstnameTooShort = 'errors.firstname_too_short',
  FirstnameShouldBeString = 'errors.firstname_should_be_string',
  LastnameTooLong = 'errors.lastname_too_long',
  LastnameTooShort = 'errors.lastname_too_short',
  LastnameShouldBeString = 'errors.lastname_should_be_string',
  PasswordTooShort = 'errors.password_too_short',
  PasswordTooLong = 'errors.password_too_long',
  TokenContainsIncorrectUser = 'errors.token_contains_incorrect_user',
  OldPasswordIncorrect = 'errors.old_password_incorrect',
  NewPasswordMatchesOld = 'errors.new_password_matches_old',
  UserAlreadyDeleted = 'errors.user_already_deleted',
  UserPermissionNotGranted = 'errors.user_permission_not_granted',
  NothingToUpdate = 'errors.nothing_to_update',
  ShouldProvideEmail = 'errors.should_provide_email',
  ShouldProvidePassword = 'errors.should_provide_password',
  ClearingDatabase = 'errors.clearing_database',
  UserNotFound = 'errors.user_not_found',
  MakeAdminShouldBeBoolean = 'errors.make_admin_should_be_boolean',
  AdminAlreadyExists = 'errors.admin_already_exists',
  SecretCodeShouldBeString = 'errors.secret_code_should_be_string',
  UserIsAlreadyAdmin = 'errors.user_is_already_admin',
}

export enum MetricsExceptionKeys {
  NotFound = 'errors.metrics_not_found',
  NameShouldBeString = 'errors.metrics_name_should_be_string',
  ValueShouldBeNumber = 'errors.metrics_value_should_be_number',
  DateShouldBeString = 'errors.metrics_date_should_be_string',
  NameTooShort = 'errors.metrics_name_too_short',
  NameTooLong = 'errors.metrics_name_too_long',
  ValueTooLow = 'errors.metrics_value_too_low',
  DesiredValueTooLow = 'errors.metrics_desired_value_too_low',
  NameAlreadyExists = 'errors.metrics_name_already_exists',
  InvalidDate = 'errors.metrics_invalid_date',
  DateAlreadyExists = 'errors.metrics_date_already_exists',
}

export enum CalendarExceptionKeys {
  NotFound = 'errors.calendar_not_found',
  NameShouldBeString = 'errors.calendar_name_should_be_string',
  NameTooShort = 'errors.calendar_name_too_short',
  NameTooLong = 'errors.calendar_name_too_long',
  NameAlreadyExists = 'errors.calendar_name_already_exists',
  CalendarDataShouldBeString = 'errors.calendar_data_should_be_string',
}

export enum ScheduleExpceptionKeys {
  NotFound = 'errors.schedule_not_found',
  NameShouldBeString = 'errors.schedule_name_should_be_string',
  NameTooShort = 'errors.schedule_name_too_short',
  NameTooLong = 'errors.schedule_name_too_long',
  NameAlreadyExists = 'errors.schedule_name_already_exists',
  ScheduleDataShouldBeString = 'errors.schedule_data_should_be_string',
  DataShouldBeAnObject = 'errors.schedule_data_should_be_an_object',
  DataDuplicateShouldBeABoolean = 'errors.schedule_data_duplicate_should_be_a_boolean',
  NoDataProvided = 'errors.schedule_no_data_provided',
  ProvidedDateIsIncorrecrtFormat = 'errors.schedule_provided_date_is_incorrect_format',
}
